---
title: "Bellabeat"
author: "Victoria"
date: "2024-11-21"
output: html_document
---
# BellaBeat Case Study
 Loading Libraries
```{r setting up libraries}
install.packages("reshape2")
library(tidyverse)      
library(lubridate)     
library(reshape2)       
library(ggplot2)        
library(dplyr)          
```

## Loading the dataset
```{r Loading CSV file}
daily_activity <- read_csv("dailyActivity_merged.csv")
```
 ## Viewing First few rows
```{r Viewing Data}
head(daily_activity)
```
 ## Plotting Daily Trends
```{r Line plot: Total Steps, Calories, and Distance over Time}
daily_activity %>% 
ggplot(aes(x = ActivityDate)) +
  geom_line(aes(y = TotalSteps, color = "Total Steps")) +
  geom_line(aes(y = Calories, color = "Calories")) +
  geom_line(aes(y = TotalDistance, color = "Total Distance")) +
  labs(title = "Daily Trends: Steps, Calories, and Distance",
       x = "Date", y = "Values",
       color = "Metric") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red", "green"))

```
 ## Bar Plot
```{r Plotting Active Minutes against Activity Level}
daily_activity %>%
  summarise(
    avg_sedentary = mean(SedentaryMinutes, na.rm = TRUE),
    avg_lightly = mean(LightlyActiveMinutes, na.rm = TRUE),
    avg_fairly = mean(FairlyActiveMinutes, na.rm = TRUE),
    avg_very = mean(VeryActiveMinutes, na.rm = TRUE)
  ) %>%
  gather(key = "Activity Level", value = "Average Minutes", -1) %>%
  ggplot(aes(x = `Activity Level`, y = `Average Minutes`, fill = `Activity Level`)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Active Minutes by Activity Level",
       x = "Activity Level", y = "Average Minutes") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")

```
 
 
